version: '3.5'
services:

###############################
   cassandra0:
    image: cassandra:3
    container_name: cassandra0
    ports:
     - 7199:7199
    expose:
    - 9042

    networks:
     - global-network-name

###############################
   cassandra1:
    image: cassandra:3
    container_name: cassandra1
    ports:
     - 9142:9042
    links:
     - cassandra0:seed
    environment:
     - CASSANDRA_SEEDS=seed
    networks:
     - global-network-name

networks:
  global-network-name:
   name: kong-net